
- name: copy file to ec2
  become: true
  copy:
    src: ~/project/artifact.tar.gz
    dest: ./
    backup: yes

- name: unzip artifacr.tar.gz
  become: true
  shell: |
    tar -xzvf artifact.tar.gz

- name: Restart the app
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start